/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * DuplexStream Engine
 *
 * The inner engine for a custom implementation of stream.Duplex
 * on the JS runtime.
 *
 * This is not meant to be directly interacted with by the user
 * rather an underlying stream implementation where stream.Duplex
 * will `_read()` from and `_write()` to.
 */
export declare class DuplexStream {
  /**
   * Read JS Accesspoint.
   *
   * Retrieve one SubscribeUpdate from the worker.
   */
  read(): Promise<object>
  /**
   * Write JS Accesspoint.
   *
   * Take in SubscribeRequest and send to the worker.
   */
  write(chunk: object): void
}

/**
 * Main client struct exposed to JavaScript via NAPI.
 *
 * The client maintains a persistent gRPC connection that is created once
 * in the constructor and reused for all subsequent operations.
 */
export declare class GrpcClient {
  /**
   * Creates a new gRPC client and establishes a connection.
   *
   * This is an async factory method that:
   * 1. Initializes the crypto provider (required for TLS)
   * 2. Builds the client with the provided configuration
   * 3. Establishes the gRPC connection
   * 4. Wraps the client for safe concurrent access
   *
   * The connection is persistent and will be reused for all subsequent operations.
   */
  static new(endpoint: string, xToken?: string | undefined | null, channelOptions?: JsChannelOptions | undefined | null): Promise<GrpcClient>
  getLatestBlockhash(request: JsGetLatestBlockhashRequest): Promise<JsGetLatestBlockhashResponse>
  ping(request: JsPingRequest): Promise<JsPongResponse>
  getBlockHeight(request: JsGetBlockHeightRequest): Promise<JsGetBlockHeightResponse>
  getSlot(request: JsGetSlotRequest): Promise<JsGetSlotResponse>
  isBlockhashValid(request: JsIsBlockhashValidRequest): Promise<JsIsBlockhashValidResponse>
  getVersion(request: JsGetVersionRequest): Promise<JsGetVersionResponse>
  subscribeReplayInfo(request: JsSubscribeReplayInfoRequest): Promise<JsSubscribeReplayInfoResponse>
  subscribe(): DuplexStream
}

export declare function decodeTxError(err: Array<number>): string

export declare function encodeTx(data: Uint8Array, encoding: WasmUiTransactionEncoding, maxSupportedTransactionVersion: number | undefined | null, showRewards: boolean): string

/**
 * ChannelOptions from JS.
 *
 * Struct to hold the channel options configuration
 * passed from JS.
 *
 * Note:
 * The type u32 is being used because of napi's built-in
 * support for u32 to number (JS) conversion.
 */
export interface JsChannelOptions {
  grpcConnectTimeout?: number
  grpcBufferSize?: number
  grpcHttp2KeepAliveInterval?: number
  grpcInitialConnectionWindowSize?: number
  grpcInitialStreamWindowSize?: number
  grpcKeepAliveTimeout?: number
  grpcTcpKeepalive?: number
  grpcTimeout?: number
  grpcMaxDecodingMessageSize?: number
  grpcMaxEncodingMessageSize?: number
  grpcDefaultCompressionAlgorithm?: JsCompressionAlgorithm
  grpcSetXRequestSnapshot?: boolean
  grpcHttp2AdaptiveWindow?: boolean
  grpcKeepAliveWhileIdle?: boolean
  grpcTcpNodelay?: boolean
}

export declare const enum JsCompressionAlgorithm {
  Gzip = 0,
  Zstd = 1
}

export interface JsGetBlockHeightRequest {
  commitment?: number
}

export interface JsGetBlockHeightResponse {
  blockHeight: string
}

export interface JsGetLatestBlockhashRequest {
  commitment?: number
}

export interface JsGetLatestBlockhashResponse {
  slot: string
  blockhash: string
  lastValidBlockHeight: string
}

export interface JsGetSlotRequest {
  commitment?: number
}

export interface JsGetSlotResponse {
  slot: string
}

export interface JsGetVersionRequest {

}

export interface JsGetVersionResponse {
  version: string
}

export interface JsIsBlockhashValidRequest {
  blockhash: string
  commitment?: number
}

export interface JsIsBlockhashValidResponse {
  slot: string
  valid: boolean
}

export interface JsPingRequest {
  count: number
}

export interface JsPongResponse {
  count: number
}

export interface JsSubscribeReplayInfoRequest {

}

export interface JsSubscribeReplayInfoResponse {
  firstAvailable?: string
}

export declare const enum WasmUiTransactionEncoding {
  Binary = 0,
  Base64 = 1,
  Base58 = 2,
  Json = 3,
  JsonParsed = 4
}
