/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class CompressedAccountFilterSet {
  constructor(maxCapacity: number)
  insert(pubkey: string): boolean
  insertBytes(pubkey: Buffer): boolean
  remove(pubkey: string): boolean
  removeBytes(pubkey: Buffer): boolean
  contains(pubkey: string): boolean
  containsBytes(pubkey: Buffer): boolean
  len(): number
  capacity(): number
  isEmpty(): boolean
  isDirty(): boolean
  takeDirty(): boolean
  toProto(): Buffer
  toAccountFilter(): Buffer
  toBlockFilter(): Buffer
}

/**
 * DuplexStream Engine
 *
 * The inner engine for a custom implementation of stream.Duplex
 * on the JS runtime.
 *
 * This is not meant to be directly interacted with by the user
 * rather an underlying stream implementation where stream.Duplex
 * will `_read()` from and `_write()` to.
 */
export declare class DuplexStream {
  /**
   * Read JS Accesspoint.
   *
   * Retrieve one encoded `SubscribeUpdate` payload from the worker.
   */
  read(): Promise<Buffer | undefined | null>
  /** Close the stream and reject future writes. */
  close(): void
  writeRaw(requestBytes: Buffer): void
}

/**
 * DuplexStreamDeshred Engine.
 *
 * Similar to `DuplexStream`, but targets the deshred pre-execution stream.
 */
export declare class DuplexStreamDeshred {
  /** Retrieve one encoded `SubscribeUpdateDeshred` payload. */
  read(): Promise<Buffer | undefined | null>
  close(): void
  writeRaw(requestBytes: Buffer): void
}

/**
 * Main client struct exposed to JavaScript via NAPI.
 *
 * The client maintains a persistent gRPC connection that is created once
 * in the constructor and reused for all subsequent operations.
 */
export declare class GrpcClient {
  /**
   * Creates a new gRPC client and establishes a connection.
   *
   * This is an async factory method that:
   * 1. Initializes the crypto provider (required for TLS)
   * 2. Builds the client with the provided configuration
   * 3. Establishes the gRPC connection
   * 4. Wraps the client for safe concurrent access
   *
   * The connection is persistent and will be reused for all subsequent operations.
   */
  static new(endpoint: string, xToken?: string | undefined | null, channelOptions?: JsChannelOptions | undefined | null, reconnectConfig?: JsReconnectConfig | undefined | null): Promise<GrpcClient>
  getLatestBlockhash(requestBytes: Buffer): Promise<Buffer>
  ping(requestBytes: Buffer): Promise<Buffer>
  getBlockHeight(requestBytes: Buffer): Promise<Buffer>
  getSlot(requestBytes: Buffer): Promise<Buffer>
  isBlockhashValid(requestBytes: Buffer): Promise<Buffer>
  getVersion(requestBytes: Buffer): Promise<Buffer>
  subscribeReplayInfo(requestBytes: Buffer): Promise<Buffer>
  /**
   * Creates a subscription stream bound to this client connection.
   *
   * The returned value is consumed by the JS SDK `ClientDuplexStream` wrapper,
   * which handles Node stream lifecycle and protobuf payload decoding.
   */
  subscribe(initialRequestBytes?: Buffer | undefined | null): Promise<DuplexStream>
  /**
   * Creates a deshred subscription stream bound to this client connection.
   *
   * Unlike `subscribe()`, this method opens the underlying gRPC stream before
   * resolving, so server-side `UNIMPLEMENTED` errors bubble to TypeScript
   * callers through the returned Promise.
   */
  subscribeDeshred(): Promise<DuplexStreamDeshred>
}

export const AUTORECONNECT_FILTER_KEY: string

export declare function decodeTxError(err: Array<number>): string

export declare function encodeDeshredTx(data: Uint8Array, encoding: WasmUiTransactionEncoding): string

export declare function encodeTx(data: Uint8Array, encoding: WasmUiTransactionEncoding, maxSupportedTransactionVersion: number | undefined | null, showRewards: boolean): string

/**
 * ChannelOptions from JS.
 *
 * Struct to hold the channel options configuration
 * passed from JS.
 *
 * Note:
 * The type u32 is being used because of napi's built-in
 * support for u32 to number (JS) conversion.
 */
export interface JsChannelOptions {
  grpcConnectTimeout?: number
  grpcBufferSize?: number
  grpcHttp2KeepAliveInterval?: number
  grpcInitialConnectionWindowSize?: number
  grpcInitialStreamWindowSize?: number
  grpcKeepAliveTimeout?: number
  grpcTcpKeepalive?: number
  grpcTimeout?: number
  grpcMaxDecodingMessageSize?: number
  grpcMaxEncodingMessageSize?: number
  grpcDefaultCompressionAlgorithm?: JsCompressionAlgorithm
  grpcSetXRequestSnapshot?: boolean
  grpcHttp2AdaptiveWindow?: boolean
  grpcKeepAliveWhileIdle?: boolean
  grpcTcpNodelay?: boolean
}

export declare const enum JsCompressionAlgorithm {
  Gzip = 0,
  Zstd = 1
}

export interface JsReconnectBackoff {
  initialIntervalMs?: number
  multiplier?: number
  maxRetries?: number
}

export interface JsReconnectConfig {
  /**
   * Omitted or true enables reconnect when this object is provided.
   * False keeps legacy no-reconnect behavior.
   */
  enabled?: boolean
  backoff?: JsReconnectBackoff
  slotRetention?: number
}

export declare const enum WasmUiTransactionEncoding {
  Binary = 0,
  Base64 = 1,
  Base58 = 2,
  Json = 3,
  JsonParsed = 4
}
