/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * DuplexStream Engine
 *
 * The inner engine for a custom implementation of stream.Duplex
 * on the JS runtime.
 *
 * This is not meant to be directly interacted with by the user
 * rather an underlying stream implementation where stream.Duplex
 * will `_read()` from and `_write()` to.
 */
export declare class DuplexStream {
  /**
   * Creates a new DuplexStream Engine.
   *
   * This constructor does the following:
   * 1. Initialize crypto provider.
   * 2. Process channel options.
   * 3. Initialize channels.
   * 4. Spawn the worker receiving requests and updates.
   * 5. Create the instance of DuplexStream Engine.
   */
  constructor(endpoint: string, xToken?: string | undefined | null, channelOptions?: object | undefined | null)
  /**
   * Read JS Accesspoint.
   *
   * Retrieve one SubscribeUpdate from the worker.
   */
  read(): Promise<object>
  /**
   * Write JS Accesspoint.
   *
   * Take in SubscribeRequest and send to the worker.
   */
  write(chunk: object): void
}

/**
 * ChannelOptions from JS.
 *
 * Struct to hold the channel options configuration
 * passed from JS.
 *
 * Note:
 * The type u32 is being used because of napi's built-in
 * support for u32 to number (JS) conversion.
 */
export interface JsChannelOptions {
  grpcConnectTimeout?: number
  grpcBufferSize?: number
  grpcHttp2KeepAliveInterval?: number
  grpcInitialConnectionWindowSize?: number
  grpcInitialStreamWindowSize?: number
  grpcKeepAliveTimeout?: number
  grpcTcpKeepalive?: number
  grpcTimeout?: number
  grpcMaxDecodingMessageSize?: number
  grpcMaxEncodingMessageSize?: number
  grpcDefaultCompressionAlgorithm?: JsCompressionAlgorithm
  grpcSetXRequestSnapshot?: boolean
  grpcHttp2AdaptiveWindow?: boolean
  grpcKeepAliveWhileIdle?: boolean
  grpcTcpNodelay?: boolean
}

export declare const enum JsCompressionAlgorithm {
  Gzip = 0,
  Zstd = 1
}
