/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class DuplexStream {
  constructor(endpoint: string, xToken?: string | undefined | null, channelOptions?: object | undefined | null)
  read(): Promise<object>
  write(chunk: object): void
}

export interface ChannelOptions {
  grpcMaxSendMessageLength?: number
  grpcMaxReceiveMessageLength?: number
  grpcKeepaliveTimeMs?: number
  grpcKeepaliveTimeoutMs?: number
  grpcKeepalivePermitWithoutCalls?: number
  grpcDefaultCompressionAlgorithm?: number
  other: Record<string, any>
}
